language: php

matrix:
    include:
      - php: 5.3
        dist: precise
      - php: 5.4
        dist: trusty
        sudo: required
      - php: 5.5
        dist: trusty
        sudo: required
      - php: 5.6
        dist: trusty
        sudo: required
      - php: 7.0
        dist: trusty
        sudo: required
      - php: 7.1
        dist: trusty
        sudo: required

before_script:
  - ./scripts/bundle-devtools.sh .
  - export GOODBY_CSV_TEST_DB_HOST=127.0.0.1
  - export GOODBY_CSV_TEST_DB_USER=root
  - export GOODBY_CSV_TEST_DB_PASS=""
  - mysql -e 'create database goodby_csv_test'
script: ./vendor/bin/phpunit --coverage-text --configuration phpunit.xml.dist
